# Use .NET 9 SDK for building and running with hot reload
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev

# Set working directory
WORKDIR /src

# Copy project file and restore dependencies
COPY ["Rest-API/Rest-API.csproj", "Rest-API/"]
COPY ["Database/Database.csproj", "Database/"]
RUN dotnet restore Rest-API/Rest-API.csproj
RUN dotnet restore Database/Database.csproj
COPY . .
WORKDIR "/src/Rest-API"

# Run the app with hot reload
ENTRYPOINT ["dotnet", "run", "--urls=http://0.0.0.0:8080"]
