{
 "title": "Healthchecks",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Overall_Uptime_Healthchecks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(healthcheck) * 50", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container_Uptime",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "up{job=\"isopruefi-frontend\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"isopruefi-backend-api\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"isopruefi-mqtt-receiver\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"isopruefi-weather-data-worker\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"traefik\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"grafana\"} * 100",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "up{job=\"alloy\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Sensor_Availability(24Hours)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT\r\n  sensor,\r\n  COUNT(DISTINCT date_trunc('minute', time)) * 100.0 / 1440\r\n    AS uptime_percent\r\nFROM uptime\r\nWHERE time >= now() - interval '24 hour' AND time <= now()\r\nGROUP BY sensor;"
    }
   ]
  },
  {
   "title": "Healthchecks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "MQTTReceiver_1_Healthcheck",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "healthcheck{instance=\"isopruefi-mqtt-receiver-1:8080\"} * 50",
       "legendFormat": "{{healthcheck}}"
      }
     ]
    },
    {
     "title": "MQTTReceiver_2_Healthcheck",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "healthcheck{instance=\"isopruefi-mqtt-receiver-2:8080\"} * 50",
       "legendFormat": "{{healthcheck}}"
      }
     ]
    },
    {
     "title": "API_1_Healthcheck",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "healthcheck{instance=\"isopruefi-backend-api-1:8080\"} * 50",
       "legendFormat": "{{healthcheck}}"
      }
     ]
    },
    {
     "title": "API_2_Healthcheck",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "healthcheck{instance=\"isopruefi-backend-api-2:8080\"} * 50",
       "legendFormat": "{{healthcheck}}"
      }
     ]
    },
    {
     "title": "GetWeatherDataWorker_1_Healthcheck",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "healthcheck{instance=\"isopruefi-get-weather-worker-1:8080\"} * 50",
       "legendFormat": "{{healthcheck}}"
      }
     ]
    },
    {
     "title": "GetWeatherDataWorker_2_Healthcheck",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "healthcheck{instance=\"isopruefi-get-weather-worker-2:8080\"} * 50",
       "legendFormat": "{{healthcheck}}"
      }
     ]
    }
   ]
  }
 ]
}