# Use .NET 9 SDK for building and running with hot reload
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS dev

# Set working directory
WORKDIR /src

# Copy project file and restore dependencies
COPY . .
RUN dotnet restore

# Set working directory to project directory
WORKDIR "/src/MQTT-Receiver"

# Run the app with hot reload
ENTRYPOINT ["dotnet", "watch", "run"]

