name: isopruefi-docker

networks:
  isopruefi-network:
    driver: bridge
  isopruefi-monitoring:

services:
  traefik:
    image: traefik:3.4.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8432:8080
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8432"

      - "traefik.http.routers.dashboard.tls.domains[0].main=*.localhost"
      - "traefik.http.routers.dashboard.tls.domains[0].sans=*.localhost"

      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme = https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto = https"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./isopruefi-docker/traefik/traefik.yml:/traefik.yml:ro"
      - "./isopruefi-docker/traefik/conf:/conf:ro"
      - "./isopruefi-docker/traefik/certs/:/var/traefik/certs/:rw"
    networks:
      - isopruefi-network
      - isopruefi-monitoring

  influxdb3:
    image: influxdb:3.2.1-core
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - type: bind
        source: ./isopruefi-docker/influx/influxdb3/data
        # Path to store data in the container
        target: /var/lib/influxdb3/data
      - type: bind
        # Path to store plugins on your host system
        source: ./isopruefi-docker/influx/influxdb3/plugins
        # Path to store plugins in the container
        target: /var/lib/influxdb3/plugins
      # - ./influx/bootstrap.sh:/docker-entrypoint-initdb.d/bootstrap.sh:ro
    networks:
      - isopruefi-network

  influxdb-explorer:
    image: influxdata/influxdb3-ui:1.0.3
    container_name: influx-explorer
    restart: unless-stopped
    ports:
      - 8888:80
      - 8889:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer.rule=Host(`explorer.localhost`)"
      - "traefik.http.routers.explorer.entrypoints=websecure"
      - "traefik.http.routers.explorer.tls=true"
      - traefik.http.services.explorer.loadbalancer.server.port=80
    command:
      - "--mode=admin"
    volumes:
      - "./isopruefi-docker/influx/explorer/db:/db:rw"
      - "./isopruefi-docker/influx/explorer/config:/app-root/config:ro"
    networks:
      - isopruefi-network
    depends_on:
      - influxdb3
      - traefik

  postgres:
    image: postgres:alpine3.21
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./isopruefi-docker/postgres:/var/lib/postgresql/data
    networks:
      - isopruefi-network
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=Isopruefi
      - POSTGRES_DB=Isopruefi

  loki:
    image: grafana/loki:3.5.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./isopruefi-docker/loki/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - isopruefi-monitoring

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./isopruefi-docker/loki/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./isopruefi-docker/loki/alerts.yml:/etc/prometheus/alerts.yml:ro
    networks:
      - isopruefi-monitoring
      - isopruefi-network

  alloy:
    image: grafana/alloy:v1.9.2
    container_name: alloy
    ports:
      - 12345:12345
      - 4317:4317
      - 4318:4318
    volumes:
      - ./isopruefi-docker/loki/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - isopruefi-monitoring
    depends_on:
      - loki
      - prometheus

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_LOG_LEVEL=warn
    #ports:
    # - 3000:3000/tcp
    networks:
      - isopruefi-monitoring
    depends_on:
      - loki
      - alloy
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh

  isopruefi-frontend-1:
    build:
      context: ./isopruefi-frontend
      dockerfile: Dockerfile-Dev
    container_name: isopruefi-frontend-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=5173"
    networks:
      - isopruefi-network
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

  isopruefi-backend-api-1:
    build:
      context: ./isopruefi-backend
      dockerfile: Rest-API/Dockerfile-Dev
    container_name: isopruefi-backend-api-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    networks:
      - isopruefi-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./secrets.env
    depends_on:
      - influxdb3
      - postgres

  isopruefi-mqtt-receiver-1:
    build:
      context: ./isopruefi-backend
      dockerfile: MQTT-Receiver-Worker/Dockerfile-Dev
    container_name: isopruefi-mqtt-receiver-1
    networks:
      - isopruefi-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./secrets.env
    depends_on:
      - influxdb3
      - postgres

  isopruefi-get-weather-worker-1:
    build:
      context: ./isopruefi-backend
      dockerfile: Get-weatherData-worker/Dockerfile-Dev
    container_name: isopruefi-get-weather-worker-1
    labels:
      - "prometheus.service=weather-worker"
      - "prometheus.instance=1"
    networks:
      - isopruefi-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - ./secrets.env
    depends_on:
      - influxdb3
      - postgres
