// <auto-generated />
using Database.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(SettingsContext))]
    partial class SettingsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Database.EntityFramework.Models.TopicSetting", b =>
                {
                    b.Property<int>("TopicSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicSettingId"));

                    b.Property<string>("DefaultTopicPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("SensorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TopicSettingId");

                    b.ToTable("TopicSettings");

                    b.HasData(
                        new
                        {
                            TopicSettingId = 1,
                            DefaultTopicPath = "dhbw/ai/si2023",
                            GroupId = 2,
                            SensorName = "SENSOR-ONE",
                            SensorType = "temp"
                        },
                        new
                        {
                            TopicSettingId = 2,
                            DefaultTopicPath = "dhbw/ai/si2023",
                            GroupId = 2,
                            SensorName = "SENSOR-TWO",
                            SensorType = "temp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
