site_name: IsoPrüfi
nav:
  - Home: index.md
  - Build: build.md
  - Dev-Guidelines: guidelines.md
  - Code Documentation: 
    - Rest-API: code/Rest-API/index.md
theme:
  name: material
  features:
    - instant_navigation
    - content.code.copy
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto        # Body text
    code: Roboto Mono   # Code blocks

plugins:
  - search
  - include_dir_to_nav
  - git-revision-date-localized
  - git-authors
 # - to-pdf
markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
