site_name: IsoPrüfi
nav:
  - Home: index.md
  - Build: build.md
  - Dev-Guidelines: guidelines.md
  - Code Documentation: 
    - Rest-API: code/Rest-API/index.md
    - MQTT-Receiver-Worker: code/MQTT-Receiver-Worker/index.md
    - MQTT-Sender: code/MQTT-Sender/index.md
    - Database: code/Database/index.md
    - UnitTests: code/UnitTests/index.md
    - Arduino: code/arduino/api.md
    - Frontend:
        - Overview: code/frontend/README.md
        - App:
            - App Overview: code/frontend/App/README.md
            - App Component: code/frontend/App/functions/default.md
        - Weather:
            - Weather Overview: code/frontend/Weather/README.md
            - Components:
                - Chart Title: code/frontend/Weather/functions/WeatherChartTitle.md
                - Temp Chart: code/frontend/Weather/functions/TempChart.md
            - Data Types:
                - WeatherEntry: code/frontend/Weather/type-aliases/WeatherEntry.md
                - WeatherData: code/frontend/Weather/variables/WeatherData.md
  - Docker: 
    - Docker Dev Environment: docker-dev.md
  - IsoPrüfi Documentation: 
    - 00 arc42 Template with Explanation: documentation/arc42-template.md
    - 01 Introduction and Goals: documentation/01_introduction_and_goals.md
    - 02 Architecture Constrains: documentation/02_architecture_constraints.md
    - 03 Context and Scope: documentation/03_context_and_scope.md
    - 04 Solution Strategy: documentation/04_solution_strategy.md
    - 05 Building Block View: documentation/05_building_block_view.md
    - 06 Runtime View: documentation/06_runtime_view.md
    - 07 Deployment View: documentation/07_deployment_view.md
    - 08 Concepts: documentation/08_concepts.md
    - 09 Architecture Decisions: documentation/09_architecture_decisions.md
    - 10 Quality Requirements: documentation/10_quality_requirements.md
    - 11 Technical Risks: documentation/11_technical_risks.md
    - 12 Glossary: documentation/12_glossary.md
  - License: license.md
theme:
  name: material
  features:
    - instant_navigation
    - content.code.copy
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto        # Body text
    code: Roboto Mono   # Code blocks

plugins:
  - search
  - include_dir_to_nav
  - git-revision-date-localized
  - git-authors
 # - to-pdf
markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
