site_name: IsoPrüfi
nav:
  - Home: index.md
  - Build: build.md
  - Dev-Guidelines: guidelines.md
  - Code Documentation: 
    - Rest-API: code/Rest-API/index.md
theme:
  name: material
  features:
    - instant_navigation
    - content.code.copy
plugins:
  - search
  - include_dir_to_nav
  - git-revision-date-localized
  - git-authors
  - to-pdf
markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.superfences
