site_name: IsoPrüfi
docs_dir: ./docs
site_url: https://deadmade.github.io/IsoPruefi/
repo_url: https://github.com/deadmade/IsoPruefi
repo_name: "deadmade/IsoPruefi"

nav:
  - Home: index.md
  - Getting Started:
      - Build & Setup: build.md
      - Docker Environment: docker-dev.md
      - Contributing: contributing.md
  - Development:
      - Guidelines: guidelines.md
      - API Reference: api-reference.md
      - API V1: api-v1.md
      - Troubleshooting: troubleshooting.md
  - Architecture Documentation:
      - 01 Introduction and Goals: documentation/01_introduction_and_goals.md
      - 02 Quality Requirements: documentation/02_quality_requirements.md
      - 03 Architecture Constraints and Solution Strategy: documentation/03_architecture_constraints_and_solution_strategy.md
      - 04 Architecture Decisions: documentation/04_architecture_decisions.md
      - 05 Context and Scope: documentation/05_context_and_scope.md
      - 06 Technical Risks: documentation/06_technical_risks.md
  - License: license.md

theme:
  name: material
  language: "en"
  features:
    - navigation.indexes
    #- navigation.sections
    #- navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto        # Body text
    code: Roboto Mono   # Code blocks

plugins:
  - search
  - minify:
      minify_html: true
  - include_dir_to_nav
  - git-revision-date-localized
  - git-authors
  - callouts
  - render_swagger:
      allow_arbitrary_locations: true
  # - to-pdf
markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_style: "default"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - admonition
  - footnotes
  - md_in_html
  - meta
  - nl2br
  - toc:
      permalink: true
      toc_depth: 2
