global:

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'discord-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'discord-critical'
    repeat_interval: 5m
  - match:
      severity: warning
    receiver: 'discord-warnings'
    repeat_interval: 30m

receivers:
- name: 'discord-notifications'
  discord_configs:
  - webhook_url: 
    title: 'IsoPruefi Alert'
    message: |
      **{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}**
      
      **Status:** {{ .Status }}
      **Severity:** {{ .CommonLabels.severity }}
      **Service:** {{ .CommonLabels.job }}
      
      {{ range .Alerts }}
      **Details:** {{ .Annotations.description }}
      **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

- name: 'discord-critical'
  discord_configs:
  - webhook_url: 
    title: '🚨 CRITICAL: IsoPruefi System Alert'
    message: |
      **{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}**
      
      **Status:** {{ .Status }}
      **Severity:** 🔴 {{ .CommonLabels.severity }}
      **Service:** {{ .CommonLabels.job }}
      
      {{ range .Alerts }}
      **Details:** {{ .Annotations.description }}
      **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}
      
      @here Please check the system immediately!

- name: 'discord-warnings'
  discord_configs:
  - webhook_url: 
    title: '⚠️ Warning: IsoPruefi System Alert'
    message: |
      **{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}**
      
      **Status:** {{ .Status }}
      **Severity:** 🟡 {{ .CommonLabels.severity }}
      **Service:** {{ .CommonLabels.job }}
      
      {{ range .Alerts }}
      **Details:** {{ .Annotations.description }}
      **Started:** {{ .StartsAt.Format "2006-01-02 15:04:05" }}
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job']