name: Run C# Integration Tests
permissions:
  contents: read

on:
  push:
  pull_request:
    
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ./isopruefi-backend

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: isopruefi_integration_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore

      - name: Run unit tests
        run: dotnet test UnitTests/UnitTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=unit_tests.trx"
        continue-on-error: false

      - name: Run integration tests
        working-directory: ./isopruefi-backend/IntegrationTests
        run: dotnet test IntegrationTests/IntegrationTests.csproj --no-build --verbosity normal --logger "trx;LogFileName=integration_tests.trx"
        env:
          ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=isopruefi_integration_test;Username=test;Password=test"
        continue-on-error: false

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            isopruefi-backend/IntegrationTests/TestResults/integration_tests.trx