permissions:
  contents: read
name: PlatformIO Unit Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # All `run:` steps will be executed from this path by default
        working-directory: ./isopruefi-arduino

    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        
        run: pio test -e native
