name: Run C# Unit Tests
permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        # All `run:` steps will be executed from this path by default
        working-directory: ./isopruefi-backend

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        working-directory: ./isopruefi-backend/UnitTests
        run: dotnet test --no-build --verbosity normal